### ISSUE TITLE
Cannot read property 'showFlow' of null

### ISSUE THREAD

**Issue by coolheaded1** [GetMetaMap/metamap-reactnative-plugin#84]
After following the official documentation, I got Cannot read property 'showFlow' of null when I click the button.

my code:
import React, {Component, useEffect} from 'react';
import {
  NativeModules,
  NativeEventEmitter,
  Button,
  View
} from 'react-native';

import {
  MetaMapRNSdk,
} from 'react-native-expo-metamap-sdk';

function App() {

    useEffect(() => {
     	const MetaMapVerifyResult = new NativeEventEmitter(NativeModules.MetaMapRNSdk)
     	MetaMapVerifyResult.addListener('verificationSuccess', (data) => console.log(data))
     	MetaMapVerifyResult.addListener('verificationCanceled', (data) => console.log(data))
    })
    const handleMetaMapClickButton = () => {
       	 MetaMapRNSdk.showFlow("610b96fb7cc893001b135505", "611101668083a1001b13cc80", {:});
      }

    return (
          <View
            style={{
              flex: 1,
              justifyContent: 'center',
              alignItems: 'center',
              backgroundColor: 'powderblue',
            }}>
            <Button onPress = {() => handleMetaMapClickButton()}  title="Click here"/>
          </View>
        );
}
export default App;

**Comment by AvoSukiasyan** [comment]
hi @coolheaded1 . let me check it on my side and get back to you

**Comment by AvoSukiasyan** [comment]
hi @coolheaded1 . this happens because you are using the react-native plugin in place of react-native. 
please use this plugin https://www.npmjs.com/package/react-native-metamap-sdk
```
import {
MetaMapRNSdk,
} from 'react-native-metamap-sdk';
```

**Comment by josephKredi** [comment]
hi @AvoSukiasyan, I just tried this and got the same thing.

import React, { useEffect } from "react";
import { NativeModules, NativeEventEmitter, Button, View } from "react-native";

import { MetaMapRNSdk } from "react-native-metamap-sdk";

export const FaceRecognition = () => {
  useEffect(() => {
    const MetaMapVerifyResult = new NativeEventEmitter(NativeModules.MetaMapRNSdk);
    MetaMapVerifyResult.addListener("verificationSuccess", (data) => console.log(data));
    MetaMapVerifyResult.addListener("verificationCanceled", (data) => console.log(data));
  }, []);

  const handleMetaMapClickButton = () => {
    MetaMapRNSdk.showFlow("610b96fb7cc893001b135505", "611101668083a1001b13cc80", {});
  };

  return (
    <View
      style={{
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "powderblue",
      }}
    >
      <Button onPress={() => handleMetaMapClickButton()} title="Click here" />
    </View>
  );
};

What am I doing wrong?
I'm running the app via expo go.

**Comment by AvoSukiasyan** [comment]
@josephKredi  for expo you should use this implementation https://www.npmjs.com/package/react-native-expo-metamap-sdk
and if it's expo you was using correct plugin. react-native-expo-metamap-sdk. 
you can ping our support team about problem and they will schedule meeting and we'll look together

**Comment by teampazi** [comment]
I have the same issue as well for over 2 weeks and it's blocking my project

**Comment by AvoSukiasyan** [comment]
Hi @teampazi . Will look it today and get back to you as soon as posible

**Comment by AvoSukiasyan** [comment]
HI @teampazi . 
The issue is fixed please use latest version of plugin [2.4.0](https://www.npmjs.com/package/react-native-expo-metamap-sdk/v/2.4.0?activeTab=versions)

**Comment by teampazi** [comment]
> HI @teampazi . The issue is fixed please use latest version of plugin [2.4.0](https://www.npmjs.com/package/react-native-expo-metamap-sdk/v/2.4.0?activeTab=versions)

This issue is not fixed see screenshot

<img width="1192" alt="Screenshot 2024-06-21 at 12 17 29 PM" src="https://github.com/GetMetaMap/metamap-reactnative-plugin/assets/84426207/72b72993-aba2-45a9-8382-559bae73c552">

<img width="1211" alt="Screenshot 2024-06-21 at 12 18 02 PM" src="https://github.com/GetMetaMap/metamap-reactnative-plugin/assets/84426207/4d0a27dc-7bd7-48bc-90b4-c69eebf9ad44">


![image](https://github.com/GetMetaMap/metamap-reactnative-plugin/assets/84426207/b23ff4cc-fb61-4ab6-bc41-e0695ce4c081)

**Comment by teampazi** [comment]
Has anyone been able to find solution to this problem because I have not for some reason this package isn't still recognized by my project. I am still unable to import the package because it doesn't seem to be installed even though i did

**Comment by Fran-Merce** [comment]
Any updates on this? I have the same problem

**Comment by leoolmosbmb** [comment]
I've already tested it. I tried all the available versions, both with Expo and without Expo, and the error persists. The package doesn't seem to be installed even though i did. Could you provide a solution? @AvoSukiasyan

**Comment by SukiasyanAvo** [comment]
@leoolmosbmb do you need expo plugin or React Native plugin.
